package org.example.enumeration;

public enum CategoryOfProduct {
    FRUITS, VEGETABLES, MEAT_SECTION, MILKY_SECTION,
    GROCERY, CANDY_SECTION,
    HOUSEHOLD_CHEMICALS, BAR, HORECA, TOBACCO_AND_ALCOHOL;
}
